SELECT USER_ID, NICKNAME, D.TOTAL_SALES AS "TOTAL_SALES"
FROM USED_GOODS_USER JOIN
(SELECT WRITER_ID ,SUM(PRICE) AS "TOTAL_SALES"
FROM USED_GOODS_BOARD
WHERE STATUS="DONE"
GROUP BY WRITER_ID
HAVING SUM(PRICE)>=700000) AS D ON USER_ID=D.WRITER_ID
ORDER BY TOTAL_SALES;